### ISSUE TITLE
contact

### ISSUE THREAD

**Issue by 4ldas** [aldas/go-nmea-client#1]
Hi, id like to talk to you in private, preferably telegram or discord however i got whatsapp instagram whatever too. I sent you an email aiready regarding this.

**Comment by aldas** [comment]
If it is about crypto or this account (name) - I am not interested.

**Comment by 4ldas** [comment]
Alr where do i contact you

**Comment by aldas** [comment]
Here, what is it about?

**Comment by 4ldas** [comment]
Ill tell you

**Comment by aldas** [comment]
Just for the record. This person has been contacting me from other means:

```
Aldas <aldasmacius@skiff.com>
1:38 AM (6 hours ago)
to me

Hi im interested in purchasing your discord username for upwards of 1k. My telegram is @lethal or discord Aldas#1337, my instagram is @gem lmk

Aldas

Secured by Skiff Mail.
```
